#!/usr/bin/env bash
set -euo pipefail

REPORT_FILE="/tmp/spectrehub-report.json"

if [ ! -f "$REPORT_FILE" ] || [ ! -s "$REPORT_FILE" ]; then
  echo "No report file found, skipping PR comment"
  exit 0
fi

# Extract data
TOTAL_ISSUES=$(jq -r '.summary.total_issues // 0' "$REPORT_FILE")
HEALTH_SCORE=$(jq -r '.summary.score_percent // 0' "$REPORT_FILE")
HEALTH_LEVEL=$(jq -r '.summary.health_score // "unknown"' "$REPORT_FILE")
TOOLS_RUN=$(jq -r '.summary.total_tools // 0' "$REPORT_FILE")

# Build health badge
case "$HEALTH_LEVEL" in
  excellent) BADGE="🟢" ;;
  good)      BADGE="🟢" ;;
  warning)   BADGE="🟡" ;;
  critical)  BADGE="🔴" ;;
  severe)    BADGE="🔴" ;;
  *)         BADGE="⚪" ;;
esac

# Build comment body
COMMENT_BODY="## ${BADGE} SpectreHub Audit

| Metric | Value |
|--------|-------|
| Health | **${HEALTH_LEVEL}** (${HEALTH_SCORE}%) |
| Issues | ${TOTAL_ISSUES} |
| Tools  | ${TOOLS_RUN} |
"

# Add issue breakdown by tool
if [ "$TOTAL_ISSUES" -gt 0 ]; then
  TOOL_TABLE=$(jq -r '.summary.issues_by_tool // {} | to_entries[] | "| \(.key) | \(.value) |"' "$REPORT_FILE")
  if [ -n "$TOOL_TABLE" ]; then
    COMMENT_BODY="${COMMENT_BODY}
### Issues by Tool

| Tool | Issues |
|------|--------|
${TOOL_TABLE}
"
  fi
fi

# Add trend if available
HAS_TREND=$(jq -r '.trend // empty | .direction' "$REPORT_FILE" 2>/dev/null || echo "")
if [ -n "$HAS_TREND" ]; then
  TREND_DIR=$(jq -r '.trend.direction' "$REPORT_FILE")
  TREND_PCT=$(jq -r '.trend.change_percent' "$REPORT_FILE")
  case "$TREND_DIR" in
    improving) TREND_ICON="📉" ;;
    degrading) TREND_ICON="📈" ;;
    *)         TREND_ICON="➡️" ;;
  esac
  COMMENT_BODY="${COMMENT_BODY}
### Trend

${TREND_ICON} **${TREND_DIR}** (${TREND_PCT}% change)
"
fi

COMMENT_BODY="${COMMENT_BODY}
---
*Generated by [SpectreHub](https://spectrehub.dev)*"

# Get PR number
PR_NUMBER="${GITHUB_EVENT_NUMBER:-}"
if [ -z "$PR_NUMBER" ]; then
  PR_NUMBER=$(jq -r '.pull_request.number // empty' "$GITHUB_EVENT_PATH" 2>/dev/null || echo "")
fi

if [ -z "$PR_NUMBER" ]; then
  echo "Could not determine PR number, skipping comment"
  exit 0
fi

# Check for existing comment and update, or create new
EXISTING_COMMENT=$(gh api \
  "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
  --jq '[.[] | select(.body | contains("SpectreHub Audit"))] | .[0].id // empty' 2>/dev/null || echo "")

if [ -n "$EXISTING_COMMENT" ]; then
  gh api \
    "repos/${GITHUB_REPOSITORY}/issues/comments/${EXISTING_COMMENT}" \
    -X PATCH \
    -f body="$COMMENT_BODY" > /dev/null
  echo "Updated existing PR comment"
else
  gh api \
    "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
    -f body="$COMMENT_BODY" > /dev/null
  echo "Posted new PR comment"
fi
